[package]
name = "request-interface"
version = "0.1.0"
authors = ["Jameson Hodge <contact@jamesonhodge.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { git = "https://github.com/near/near-sdk-rs.git", rev="249dacdcd3fd34bc00f0895a275f33f05cd910c1" }
flux-sdk = { git = "https://github.com/fluxprotocol/flux-sdk-rs.git", rev="4331a496fd9e527082fd351dc6068466b3471a0f" }
serde = "1.0.118"
